---
title: "Assigment - Data Driven Decision Making"
author: name author here
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

Search Youtube for a suitable business case example on data driven decision making and copy the embed code below.

<---- Watch this video if you don't know how to embed video's ---->

<iframe width="560" height="315" src="https://youtu.be/6GZzrugo8rY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<---- Replace this video with your business case example ---->


## Why was data driven decision making (3DM) useful in this business case?

Overall, Netflix provides an improved personalized customer experienced based on data analytics and decision making. (5 minutes learning, 2021). 

## How did the organization apply 3DM?

Netflix has multiple uses of data analytics to make business decisions based on data:

- Link prediction (recommendations of videos after watching one based on content-based filtering (see figure 1))
- Regression (determine a numerical value on how much someone is likely to watch a different show, based on historical consumer data)
- Profiling (they make up a typical profile of groupings to determine what features a new show should have so that the profiles of the mass would like the show (based on the available data)) An example of such show is House of Cards (5 minutes learning, 2021).
- Success rate prediction of shows. Netflix predicts the success rate of shows based on data analytics to give shape to shows (house of cards). This success rate is said to have led to 80% of Netflix shows being a 'success' according to 5 minutes learning, 2021. This predicament of a success rate has also led to helping Netflix decrease promotional activities and campaigns.
- Co-occurence grouping. Someone watches show A after finishing show B. Another person watches show B and finishes it. Netflix then recommends show A to the other person based on what the first person watched in combination with show A.This data mining methodology is displayed under collaborative filtering in figure 1. 

## What can the organization do with 3DM that they couldn’t do before?

- Create a success rate for shows. The rate is created through creating algorithms (data mining) (5 minutes learning, 2021). 
- Improve the personalized customer experience.
- Make shows in a way that they are conform the wants of the customer.

hh
EMBED PICTURE

